import 'dotenv/config';
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { apis } from "./drizzle/schema";
import type { InsertApi } from "./drizzle/schema";
import { nanoid } from "nanoid";

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  console.error("DATABASE_URL is not set. Please set it in your environment or .env file.");
  process.exit(1);
}
const client = postgres(databaseUrl);
const db = drizzle(client);
const generateId = () => nanoid(16);

const mapStatus = (excelStatus: string): "active" | "deprecated" | "beta" => {
  const status = excelStatus?.toLowerCase() || "";
  if (status.includes("active")) return "active";
  if (status.includes("deactivated") || status.includes("inactive")) return "deprecated";
  if (status.includes("new")) return "beta";
  return "active";
};

const extractMethod = (integrationType: string): "GET" | "POST" | "PUT" | "DELETE" | "PATCH" => {
  const type = integrationType?.toUpperCase() || "";
  if (type.includes("GET")) return "GET";
  if (type.includes("POST")) return "POST";
  if (type.includes("PUT")) return "PUT";
  if (type.includes("DELETE")) return "DELETE";
  if (type.includes("PATCH")) return "PATCH";
  // Default to POST for SOAP services, GET for REST
  return type.includes("REST") ? "GET" : "POST";
};

const excelApis: InsertApi[] = [
  {
    id: generateId(),
    name: "AzureBCXGetAuthToken",
    serviceName: "AzureBCXGetAuthToken",
    description: "A technical service for authenticating to AzureBCX.",
    serviceDescription: "A technical service for authenticating to AzureBCX.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/AzureBCXGetAuthToken",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "EI-ESB PublishBillingAccountInformation, EI-ESB GetCustomerAccounts, EI-ESB GetCustomerDedails, EI-ESB GetGeographicSite, EI-ESB GetCRMAddressDetails, EI-ESB GetContacts",
    backends: "Azure API Manager_BCX POST {key}/oauth2/v2.0/token",
    complexity: "Simple",
    serviceType: "Technical",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "CreateChange",
    serviceName: "CreateChange",
    description: "This is a synchronous business service that will be used to create a change object in BSD and return a change or reference number.",
    serviceDescription: "This is a synchronous business service that will be used to create a change object in BSD and return a change or reference number.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/CreateChange",
    method: "POST",
    businessUnit: "Across BU",
    clientsImpacted: "EIB_Order_ProvisioningRequest",
    backends: "Business Service Desk (BSD), SmartFax (NGN Telecoms) ( (via API Gateway - B2B Gateway (EAM)_Telkom)), BOSS (via API Gateway - B2B Gateway (EAM)_Telkom)",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "CreateIncident",
    serviceName: "CreateIncident",
    description: "This service will handle the creation of new incidents on the BCC service desk.",
    serviceDescription: "This service will handle the creation of new incidents on the BCC service desk.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/CreateIncident",
    method: "POST",
    businessUnit: "Across BU",
    clientsImpacted: "SBSA (via API Gateway - B2B Gateway (EAM))",
    backends: "BCC",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "CreateSalesOpportunity",
    serviceName: "CreateSalesOpportunity",
    description: "This is a synchronous service which will be used to create a Sales Opportunity.",
    serviceDescription: "This is a synchronous service which will be used to create a Sales Opportunity.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/CreateSalesOpportunity",
    method: "POST",
    businessUnit: "Across BU",
    clientsImpacted: "SalesForce.com, BCC, Wholesale Portal, CSB eCommerce(via API Gateway – B2B Gateway (EAM)_Telkom), SFE (via API Gateway – B2B Gateway (EAM)_Telkom), Whatsapp (via API Gateway – B2B Gateway (Internal)_Consumer), Telkom App (via API Gateway – B2B Gateway (EAM)_Telkom)",
    backends: "CRMClarify12",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "CreateSalesOpportunityTeamMember",
    serviceName: "CreateSalesOpportunityTeamMember",
    description: "This is a synchronous service which will add a team member of the sales team, to an existing opportunity so that this team member is able to manage the opportunity.",
    serviceDescription: "This is a synchronous service which will add a team member of the sales team, to an existing opportunity so that this team member is able to manage the opportunity.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/CreateSalesOpportunityTeamMember",
    method: "POST",
    businessUnit: "OpenServe",
    clientsImpacted: "WholeSale Portal",
    backends: "CRMClarify12",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "CreateTicket",
    serviceName: "CreateTicket",
    description: "This service will be used to create a new Ticket. This service can be called by many client systems and can be provided by different backend systems based on the information supplied.",
    serviceDescription: "This service will be used to create a new Ticket. This service can be called by many client systems and can be provided by different backend systems based on the information supplied.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/CreateTicket",
    method: "POST",
    businessUnit: "Consumer",
    clientsImpacted: "ISP, FMS, Azure APIM, TM Forum API, Service View, ITSD, UTS, Shoprite, Intranet Employee Escalations, API Gateway(Internal)_Consumer, SFE, IBM Resilient, Service View NOMIF, SPH, CBS, NFMS, ITSM BMC via API Gateway - B2B Gateway (EAM)_Telkom, Vodacom via API Gateway - B2B Gateway (EAM)_Telkom, OWS via API Gateway - B2B Gateway (EAM)_Telkom, Cortex IA: Intelligence Automation (via API Gateway - B2B Gateway (EAM)_Telkom), BOSS via API Gateway - B2B Gateway (EAM)_Telkom, TMCM, Webforce, EI-ESB SMARTSCreateTicket, SLIM, ETL Team Scripts, Openserve-ESB: Enterprise Service Bus",
    backends: "BL&D, ITSD, UTS, Portal, UB (FMS), SPH(BSD_GRA,BSD_CES), CBS, Webforce, Archibus via API Gateway - B2B Gateway (EAM), ITSM, Bidvest SAP via API Gateway - B2B Gateway (EAM), TIBill (Telkom Internet Billing System), NGBSS CRM, RPA, EI-ESB GetCustomerDetails, Vodacom via API Gateway - B2B Gateway (EAM)_Telkom, OWS via API Gateway - B2B Gateway (EAM)_Telkom, BOSS via API Gateway - B2B Gateway (EAM)_Telkom, Openserve-ESB: Enterprise Service Bus, TMCM, EI-ESB GetEntityMigrationStatusOpenserve, Rimini Street Boomi API Management",
    complexity: "Complex",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: true,
    popularity: 100
  },
  {
    id: generateId(),
    name: "ForeignExchangeRate",
    serviceName: "ForeignExchangeRate (GET /latest)",
    description: "The Exchange Rate API enables the consumer of the API to retrieve the latest forein exchange rate for specified currency as published by Telkom Group Treasury",
    serviceDescription: "The Exchange Rate API enables the consumer of the API to retrieve the latest forein exchange rate for specified currency as published by Telkom Group Treasury",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/ForeignExchangeRate/latest",
    method: "GET",
    businessUnit: "BCX/IT",
    clientsImpacted: "IPAAdaptation",
    backends: "EI-ESB GetSystemAuthenticationToken; SAP CPI_BCX (SAP SAP Cloud Platform Integrator)",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "REST",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "GetConfigurationItemDetail",
    serviceName: "GetConfigurationItemDetail",
    description: "This is a Synchronous service which will be used to get the latest Configuration Item(CI) detail from BCC. This is a pull mechanism that applies to the active CIs.",
    serviceDescription: "This is a Synchronous service which will be used to get the latest Configuration Item(CI) detail from BCC. This is a pull mechanism that applies to the active CIs.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/GetConfigurationItemDetail",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Shoprite SD:Service Desk",
    backends: "BCC",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "GetGeographicSite",
    serviceName: "GetGeographicSite",
    description: "This service will be used to retrieve one or more sites of a customer using a valid AccountID.",
    serviceDescription: "This service will be used to retrieve one or more sites of a customer using a valid AccountID.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/GetGeographicSite",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "EI-EIB Customer_AllSitesQuery",
    backends: "Azure API Manager_BCX (via API Gateway – B2B Gateway (EAM)_Telkom), EI-ESB AzureBCXGetAuthToken",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "GetProductCatalogue",
    serviceName: "GetProductCatalogue",
    description: "This is a Synchronous service which will retrieve the details of a product offering as defined in the Electronic Product Catalogue dump in the BL&D tables.",
    serviceDescription: "This is a Synchronous service which will retrieve the details of a product offering as defined in the Electronic Product Catalogue dump in the BL&D tables.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/GetProductCatalogue",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "TM Forum API (BCX API Gateway)",
    backends: "BL&D.ProductSpecification,BL&D.ProductOffering",
    complexity: "Medium",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "GetTicketDetail",
    serviceName: "GetTicketDetail",
    description: "This is a synchronous service which will return the detailed ticket information.",
    serviceDescription: "This is a synchronous service which will return the detailed ticket information.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/GetTicketDetail",
    method: "POST",
    businessUnit: "Across BU",
    clientsImpacted: "Shoprite,portal,ePortal API Gateway_BCX(TMF_API), API Gateway_Consumer(Internal), SFE, Azure API Manager_BCX(Salesforce) (via API Gateway - B2B Gateway (EAM))",
    backends: "SPH(BSD-BCC)",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "GetTILinkedCustomerDetail",
    serviceName: "GetTILinkedCustomerDetail",
    description: "This is a Synchronous service which will retrieve the ISP customer and product for the specified Telkom Internet service. This service will also cater for an ISP username as input.",
    serviceDescription: "This is a Synchronous service which will retrieve the ISP customer and product for the specified Telkom Internet service. This service will also cater for an ISP username as input.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/GetTILinkedCustomerDetail",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "ePortal API Gateway_BCX(TMF_API)",
    backends: "LPDH (LPDH_EXT_SVC_INTERFACE.GetISPCustomerServices)",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "GetTIServiceUsageHistory",
    serviceName: "GetTIServiceUsageHistory",
    description: "No documentation found in SP or DMC",
    serviceDescription: "No documentation found in SP or DMC",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/GetTIServiceUsageHistory",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "ePortal API Gateway_BCX(TMF_API)",
    backends: "ISP",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "IPAAdaptation",
    serviceName: "IPAAdaptation",
    description: "This is a generic adaptation service that used to perform vaious protocol translations and message transformation where IPActivator needs to consume EI ESB services and/or APIs",
    serviceDescription: "This is a generic adaptation service that used to perform vaious protocol translations and message transformation where IPActivator needs to consume EI ESB services and/or APIs",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/IPAAdaptation",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "IPActivator",
    backends: "ServiceActivationAndConfiguration (POST /Service), ExchageRate (GET /latest)",
    complexity: "Simple",
    serviceType: "Adaptation",
    integrationType: "JMS",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "LogTicketComment",
    serviceName: "LogTicketComment",
    description: "This service will be used to log a comment on a ticket. This service can be called by many client systems and can be provided by different backend systems based on the information supplied. A Multi-directional service.",
    serviceDescription: "This service will be used to log a comment on a ticket. This service can be called by many client systems and can be provided by different backend systems based on the information supplied. A Multi-directional service.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/LogTicketComment",
    method: "POST",
    businessUnit: "Across BU",
    clientsImpacted: "Shoprite via EAM,SPH,CBS,Webforce, ServiceView,TMCM, ITSM via EAM, UTS, ITSD, e-Portal API Gateway Openserve, ePortal-API Gateway BCX, IBM Resilient, Azure APIM (API Management_Openserve) , SFE, API Gateway_Consumer (Internal),ServiceView NOMIF, Vodacom, OWS, Automator, Cortex (via API Gateway - B2B Gateway (EAM)_Telkom), Vodacom (via API Gateway - B2B Gateway (EAM)_Telkom), OWS (via API Gateway - B2B Gateway (EAM)_Telkom), BOSS (via API Gateway - B2B Gateway (EAM)_Telkom), ICRES(via API Gateway - B2B Gateway (EAM)_Telkom), Bidvest SAP(via API Gateway - B2B Gateway (EAM)_Telkom), EI-ESB SMARTSLogTicketComment, Rimini Street Boomi API Management ,Genesys via API Gateway - B2B Gateway (EAM)_Telkom, EI-ESB UpdateTicketStatus, Openserve-ESB: Enterprise Service Bus",
    backends: "Portal APIGateway Openserve, CBS, ITSD, NFMS, ServiceView, UTS,BL&D,UB(FMS),Shoprite via Mashery,SPH(BSD_GRA,BSD_CES),Webforce, ePortal-API Gateway BCX,TMCM,NGBSS CRM, ITSM (via API Gateway – B2B Gateway (EAM)_Telkom), IBM Resilient, ServiceView NOMIF, Vodacom (via API Gateway - B2B Gateway (EAM)_Telkom), OWS (via API Gateway - B2B Gateway (EAM)_Telkom), BOSS (via API Gateway - B2B Gateway (EAM)_Telkom), Openserve-ESB: Enterprise Service Bus, ICRES (via API Gateway - B2B Gateway (EAM)_Telkom), Bidvest SAP (via API Gateway - B2B Gateway (EAM)_Telkom), Rimini Street Boomi API Management , ABSA_SNOW (via API Gateway - B2B Gateway (EAM)_Telkom),ISP_SNOW(ServiceNow:IT Service Desk Tool)(via API Gateway -B2B Gateway (EAM)_Telkom)",
    complexity: "Medium",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: true,
    popularity: 80
  },
  {
    id: generateId(),
    name: "NotifyAddressVerificationResult",
    serviceName: "NotifyAddressVerificationResult",
    description: "This is a synchronous service used to send a verified address response to the Client. The Service is used in conjunction with RequestAddressVerification (please refer to R-9), GIS SDE will verify the address, resolve it if possible and send the results back to the client via NotifyAddressVerificationResult.",
    serviceDescription: "This is a synchronous service used to send a verified address response to the Client. The Service is used in conjunction with RequestAddressVerification (please refer to R-9), GIS SDE will verify the address, resolve it if possible and send the results back to the client via NotifyAddressVerificationResult.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/NotifyAddressVerificationResult",
    method: "POST",
    businessUnit: "Across BU",
    clientsImpacted: "GIS SDE: Spatial Database Engine",
    backends: "CRM Clarify 12,NGBSS CRM, Portal,TMFORUM API,CBS",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "PublishBillingAccountInformation",
    serviceName: "PublishBillingAccountInformation",
    description: "This service will be used to publish billing account information.",
    serviceDescription: "This service will be used to publish billing account information.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/PublishBillingAccountInformation",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Billing systems",
    complexity: "Medium",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "PublishCustomerAccountInformation",
    serviceName: "PublishCustomerAccountInformation",
    description: "This service will be used to publish customer account information.",
    serviceDescription: "This service will be used to publish customer account information.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/PublishCustomerAccountInformation",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Customer management systems",
    complexity: "Medium",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "PublishProductOrderInformation",
    serviceName: "PublishProductOrderInformation",
    description: "This service will be used to publish product order information.",
    serviceDescription: "This service will be used to publish product order information.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/PublishProductOrderInformation",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Order management systems",
    complexity: "Medium",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "QueryCustomerAccount",
    serviceName: "QueryCustomerAccount",
    description: "This service will be used to query customer account information.",
    serviceDescription: "This service will be used to query customer account information.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/QueryCustomerAccount",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Customer management systems",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "RequestAddressVerification",
    serviceName: "RequestAddressVerification",
    description: "This service will be used to request address verification from GIS.",
    serviceDescription: "This service will be used to request address verification from GIS.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/RequestAddressVerification",
    method: "POST",
    businessUnit: "Across BU",
    clientsImpacted: "Various systems",
    backends: "GIS SDE: Spatial Database Engine",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "RetrieveProductInventory",
    serviceName: "RetrieveProductInventory",
    description: "This service will be used to retrieve product inventory information.",
    serviceDescription: "This service will be used to retrieve product inventory information.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/RetrieveProductInventory",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Inventory management systems",
    complexity: "Medium",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "ServiceActivationAndConfiguration",
    serviceName: "ServiceActivationAndConfiguration",
    description: "This service will be used to activate and configure services.",
    serviceDescription: "This service will be used to activate and configure services.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/ServiceActivationAndConfiguration",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Service provisioning systems",
    complexity: "Complex",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "UpdateCustomerAccount",
    serviceName: "UpdateCustomerAccount",
    description: "This service will be used to update customer account information.",
    serviceDescription: "This service will be used to update customer account information.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/UpdateCustomerAccount",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Customer management systems",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "UpdateTicketStatus",
    serviceName: "UpdateTicketStatus",
    description: "This service will be used to update ticket status.",
    serviceDescription: "This service will be used to update ticket status.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/UpdateTicketStatus",
    method: "POST",
    businessUnit: "Across BU",
    clientsImpacted: "Various systems",
    backends: "Service desk systems",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "ValidateCustomerCredentials",
    serviceName: "ValidateCustomerCredentials",
    description: "This service will be used to validate customer credentials.",
    serviceDescription: "This service will be used to validate customer credentials.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/ValidateCustomerCredentials",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Authentication systems",
    complexity: "Simple",
    serviceType: "Technical",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "ValidateProductOffering",
    serviceName: "ValidateProductOffering",
    description: "This service will be used to validate product offerings.",
    serviceDescription: "This service will be used to validate product offerings.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/ValidateProductOffering",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Product catalog systems",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "VerifyServiceAvailability",
    serviceName: "VerifyServiceAvailability",
    description: "This service will be used to verify service availability.",
    serviceDescription: "This service will be used to verify service availability.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/VerifyServiceAvailability",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Network management systems",
    complexity: "Medium",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "GetCustomerDetails",
    serviceName: "GetCustomerDetails",
    description: "This service will be used to retrieve detailed customer information.",
    serviceDescription: "This service will be used to retrieve detailed customer information.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/GetCustomerDetails",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Customer management systems",
    complexity: "Simple",
    serviceType: "Business",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "GetSystemAuthenticationToken",
    serviceName: "GetSystemAuthenticationToken",
    description: "This service will be used to retrieve system authentication tokens.",
    serviceDescription: "This service will be used to retrieve system authentication tokens.",
    categoryId: "cat-esb-services",
    version: "1.0",
    status: mapStatus("Active"),
    endpoint: "/esb/GetSystemAuthenticationToken",
    method: "POST",
    businessUnit: "BCX/IT",
    clientsImpacted: "Various systems",
    backends: "Authentication systems",
    complexity: "Simple",
    serviceType: "Technical",
    integrationType: "SOAP",
    featured: false,
    popularity: 0
  }
];

const pdfApis: InsertApi[] = [
  {
    id: generateId(),
    name: "Test SSL",
    serviceName: "Test SSL",
    description: "Once you have imported the SXI Certificate call this method. If you see 'SSL communication is Working!!' then you have successfully imported the certificate into your app.",
    categoryId: "cat-general",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/ssl-test",
    method: "GET" as const,
    responseFormat: "*/*",
    authRequired: false,
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "Get the current version",
    serviceName: "Get the current version",
    description: "Get the current version",
    categoryId: "cat-general",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/version",
    method: "GET" as const,
    responseFormat: "string",
    authRequired: false,
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "Execute the defined Candidate",
    serviceName: "Execute the defined Candidate",
    description: "This will instruct the API to execute the candidate that has been defined in the URL and configured in the XLayer Secure Remote Execution application",
    categoryId: "cat-secure-remote-exec",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/sre/execCandidate",
    method: "GET" as const,
    responseFormat: "application/json",
    authRequired: true,
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    parameters: JSON.stringify([
      { name: "id", type: "string", required: true, description: "The ID of the candidate to Execute" }
    ]),
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "Execute the defined Candidate and include the Arguments from the body",
    serviceName: "Execute the defined Candidate with Args",
    description: "This will instruct the API to execute the candidate that has been defined in the URL and configured in the XLayer Secure Remote Execution application - It will also check the JSON body for additional arguments to provide the script that is being called. NOTE: ANY Arguments defined in the BODY will be added AFTER the arguments defined in the Candidates.xml configuration file. Arguments MUST have the following format: 'arg1..n':'Some Arg to process'. Arguments will be sorted and ordered by the number following the arg prefix in numerical order",
    categoryId: "cat-secure-remote-exec",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/sre/execCandidateWithArgs",
    method: "POST" as const,
    responseFormat: "application/json",
    authRequired: true,
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    parameters: JSON.stringify([
      { name: "id", type: "string", required: true, description: "The ID of the candidate to Execute" }
    ]),
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "Get the details of a specific candidate",
    serviceName: "Get Candidate Details",
    description: "Returns the details of the (commands/scripts) that have been configured for execution by the XLayer Secure Remote Execution for a specific candidate.",
    categoryId: "cat-secure-remote-exec",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/sre/getCandidate",
    method: "GET" as const,
    responseFormat: "application/json",
    authRequired: true,
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    parameters: JSON.stringify([
      { name: "id", type: "string", required: true, description: "The ID of the candidate to fetch details for" }
    ]),
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "Get the list of execution candidates",
    serviceName: "Get Candidates List",
    description: "Returns the list of candidates (commands/scripts) that have been configured for execution by the XLayer Secure Remote Execution.",
    categoryId: "cat-secure-remote-exec",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/sre/getCandidates",
    method: "GET" as const,
    responseFormat: "application/json",
    authRequired: true,
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "Universal Asynchronous API Call",
    serviceName: "Universal Async API",
    description: "This will NOT wait for a response from XLayer. The transaction payload can contain ANY values and will simply be added to the signal registry. The additional fields needed for a signal registry entry will be automatically populated with default values. NOTE: The payload must be a VALID JSON object.",
    categoryId: "cat-universal-transactions",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/api/uniAsync",
    method: "POST" as const,
    responseFormat: "application/json",
    authRequired: true,
    timeout: "No wait",
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: true,
    popularity: 50
  },
  {
    id: generateId(),
    name: "Universal Asynchronous API Call - x-www-form-urlencoded",
    serviceName: "Universal Async API (Form)",
    description: "This will NOT wait for a response from XLayer. The transaction does NOT need a payload in the body but should have parameters using Content-Type x-www-form-urlencoded. ANY values can be included. These will simply be added to the signal registry. The additional fields needed for a signal registry entry will be automatically populated with default values.",
    categoryId: "cat-universal-transactions",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/api/uniAsync_params",
    method: "POST" as const,
    responseFormat: "application/json",
    authRequired: true,
    timeout: "No wait",
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "A Universal GET that can take any number of parameters that will be sent to XLayer",
    serviceName: "Universal GET",
    description: "This will NOT wait for a response from XLayer. The transaction will be determined from the list of Key Value Pairs provide on the URL and will simply be added to the signal registry. The additional fields needed for a signal registry entry will be automatically populated with default values. NOTE: You cannot test this API from inside swagger due to a limitation in the Swagger implementation. To test please use something like Postman or SoapUI",
    categoryId: "cat-universal-transactions",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/api/uniGet",
    method: "GET" as const,
    responseFormat: "*/*",
    authRequired: true,
    timeout: "No wait",
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "Universal Synchronous API Call",
    serviceName: "Universal Sync API",
    description: "This call will wait for a preconfigured time period for a response from XLayer (Default 60 seconds). If a response is received before the timeout that response will be sent back to the calling client. The transaction payload can contain ANY values and will simply be added to the signal registry. The additional fields needed for a signal registry entry will be automatically populated with default values. NOTE: The payload must be a VALID JSON object.",
    categoryId: "cat-universal-transactions",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/api/uniSync",
    method: "POST" as const,
    responseFormat: "application/json",
    authRequired: true,
    timeout: "60 seconds (default)",
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: true,
    popularity: 60
  },
  {
    id: generateId(),
    name: "Upload file to XLayer",
    serviceName: "Upload File",
    description: "Methods to Upload Attachments",
    categoryId: "cat-upload-files",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/file/upload",
    method: "POST" as const,
    responseFormat: "multipart/form-data",
    authRequired: true,
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: false,
    popularity: 0
  },
  {
    id: generateId(),
    name: "XLayer Transactions",
    serviceName: "XLayer Transactions",
    description: "Methods to trigger XLayer using defined fields",
    categoryId: "cat-xlayer-transactions",
    version: "5.4.1",
    status: "active" as const,
    endpoint: "/xlayer/transactions",
    method: "POST" as const,
    responseFormat: "application/json",
    authRequired: true,
    swaggerUrl: "https://smtapi.ourservicedesk.com/swagger-ui/index.html",
    apiVersion: "5.4.1",
    featured: false,
    popularity: 0
  }
];

export async function seedApis() {
  try {
    console.log('🌱 Starting API seeding...\n');
    
    console.log('📊 Seeding Excel APIs (ESB Services)...');
    for (const api of excelApis) {
      await db.insert(apis).values(api);
      console.log(`  ✓ Created API: ${api.name}`);
    }
    console.log(`✅ Seeded ${excelApis.length} Excel APIs\n`);
    
    console.log('📄 Seeding PDF APIs (XLayer REST APIs)...');
    for (const api of pdfApis) {
      await db.insert(apis).values(api);
      console.log(`  ✓ Created API: ${api.name}`);
    }
    console.log(`✅ Seeded ${pdfApis.length} PDF APIs\n`);
    
    console.log('🎉 Seeding completed successfully!');
    console.log(`\n📈 Summary:`);
    console.log(`  • Excel APIs: ${excelApis.length}`);
    console.log(`  • PDF APIs: ${pdfApis.length}`);
    console.log(`  • Total APIs: ${excelApis.length + pdfApis.length}`);
    
  } catch (error) {
    console.error('❌ Error seeding APIs:', error);
    throw error;
  }
}
seedApis()
  .then(() => {
    console.log('Seed script finished successfully!');
    process.exit(0);
  })
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  });