CREATE TYPE "public"."api_method" AS ENUM('GET', 'POST', 'PUT', 'DELETE', 'PATCH');--> statement-breakpoint
CREATE TYPE "public"."api_status" AS ENUM('active', 'deprecated', 'beta');--> statement-breakpoint
CREATE TABLE "apis" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"categoryId" varchar(64) NOT NULL,
	"version" varchar(50) NOT NULL,
	"status" "api_status" DEFAULT 'active' NOT NULL,
	"endpoint" varchar(500) NOT NULL,
	"method" "api_method" NOT NULL,
	"pricing" varchar(100),
	"rateLimit" varchar(100),
	"documentation" text,
	"featured" boolean DEFAULT false,
	"popularity" integer DEFAULT 0,
	"createdAt" timestamp DEFAULT now(),
	"updatedAt" timestamp DEFAULT now(),
	"businessUnit" varchar(255),
	"serviceName" varchar(255),
	"clientsImpacted" text,
	"backends" text,
	"complexity" varchar(100),
	"serviceType" varchar(100),
	"integrationType" varchar(100),
	"serviceDescription" text,
	"swaggerUrl" varchar(500),
	"apiVersion" varchar(50),
	"authRequired" boolean,
	"responseFormat" varchar(100),
	"timeout" varchar(50),
	"parameters" text,
	"area" varchar(255)
);
